import type { CalendarEvent } from "../types"

const mockEvents: CalendarEvent[] = [
  {
    id: 1,
    summary: "1st Round",
    desc: "1st Round",
    start: "2025-06-15T01:00:00+05:30",
    end: "2025-06-15T01:40:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      P: 8,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "Django developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "Django",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "Django developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "Django",
      jobRequest_Description: "asfffasf",
    },
  },
  {
    id: 2,
    summary: "Test",
    desc: "Test",
    start: "2025-06-15T01:00:00+05:30",
    end: "2025-06-15T01:40:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      p: 7,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "React developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "React",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "React developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "React",
      jobRequest_Description: "asfffasf",
    },
  },
  {
    id: 3,
    summary: "2nd Round",
    desc: "2nd Round",
    start: "2025-06-26T03:00:00+05:30",
    end: "2025-06-26T04:00:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "NodeJs developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "NodeJs",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "NodeJs developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "NodeJs",
      jobRequest_Description: "asfffasf",
    },
  },
   {
    id: 4,
    summary: "Final Round",
    desc: "Final Round",
    start: "2025-06-16T20:00:00+05:30",
    end: "2025-06-16T21:00:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "MERN developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "MERN",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "MERN developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "MERN",
      jobRequest_Description: "asfffasf",
    },
  },
   {
    id: 5,
    summary: "HR Round",
    desc: "HR Round",
    start: "2025-06-24T04:00:00+05:30",
    end: "2025-06-24T21:00:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "AI developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "AI",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "AI developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "AI",
      jobRequest_Description: "asfffasf",
    },
  },
   {
    id: 6,
    summary: "2nd Round",
    desc: "2nd Round",
    start: "2025-06-23T03:00:00+05:30",
    end: "2025-06-23T06:00:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "Frontend developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "Frontend",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "Frontend developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "Frontend",
      jobRequest_Description: "asfffasf",
    },
  },
  {
    id: 5,
    summary: "HR Round",
    desc: "HR Round",
    start: "2025-06-24T04:00:00+05:30",
    end: "2025-06-24T07:00:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "AI",
        candidate_lastName: "Developer",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "AIdeveloper@gmail.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "AIUser@dataterrain.com",
        username: "AI_hr",
        firstName: "AIUser",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "AI developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "AI",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "AI developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "AI",
      jobRequest_Description: "asfffasf",
    },
  },
  {
    id: 8,
    summary: "HR Round",
    desc: "HR Round",
    start: "2025-06-24T04:30:00+05:30",
    end: "2025-06-24T21:00:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
      },
      handled_by: {
        id: 3,
        last_login: null,
        userEmail: "vinodhini_hr@dataterrain.com",
        username: "vinodhini_hr",
        firstName: "Vinodhini",
        lastName: "HR",
        userRole: "hr_employee",
      },
      job_id: {
        id: 11,
        jobRequest_Title: "AI developer",
        jobRequest_Role: "software engineer",
        jobRequest_KeySkills: "AI",
        jobRequest_Description: "asfffasf",
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "AI developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "AI",
      jobRequest_Description: "asfffasf",
    },
  },
  
]

export async function fetchCalendarEvents(_startDate: Date, _endDate: Date): Promise<CalendarEvent[]> {
  await new Promise((resolve) => setTimeout(resolve, 500))

  return mockEvents
}

export async function fetchEventDetails(eventId: number): Promise<CalendarEvent> {
  await new Promise((resolve) => setTimeout(resolve, 300))

  const event = mockEvents.find((e) => e.id === eventId)
  if (!event) {
    throw new Error("Event not found")
  }

  return event
}
